#!/bin/bash
#SBATCH --job-name=controlk25sig0.0001msteps200000000expgrid
#SBATCH --output=controlk25sig0.0001msteps200000000expgrid.out
#SBATCH --error=controlk25sig0.0001msteps200000000expgrid.err
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g-3
#SBATCH -N 1
#SBATCH --workdir=/home/codylong/wishart/control/workdir
cd /home/codylong/wishart/control/
mpirun -prot -srun -n 1 python ControlClasses.py 200000000 grid 25 1e-50 0.0001