#!/bin/bash
#SBATCH --job-name=controlk25sig0.0001msteps200000000exprand
#SBATCH --output=controlk25sig0.0001msteps200000000exprand.out
#SBATCH --error=controlk25sig0.0001msteps200000000exprand.err
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g-3
#SBATCH -N 1
#SBATCH --workdir=/home/codylong/wishart/control/workdir
cd /home/codylong/wishart/control/
mpirun -prot -srun -n 1 python ControlClasses.py 200000000 rand 25 1e-50 0.0001