#!/bin/bash
#SBATCH --job-name=controlk10sig0.0001msteps2000000000expgridmtypeload
#SBATCH --output=controlk10sig0.0001msteps2000000000expgridmtypeload.out
#SBATCH --error=controlk10sig0.0001msteps2000000000expgridmtypeload.err
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g-4
#SBATCH -N 1
#SBATCH --workdir=/home/codylong/wishart/control/workdir
cd /home/codylong/wishart/control/
mpirun -prot -srun -n 32 python ControlClasses.py 2000000000 grid 10 1e-50 0.0001 load