#!/bin/bash
#SBATCH --job-name=cc-10k-v0nmod10s20000000000p1e1e-50sig0.0001g0.99b0.1_lstm
#SBATCH --output=cc-10k-v0nmod10s20000000000p1e1e-50sig0.0001g0.99b0.1_lstm2.out
#SBATCH --error=cc-10k-v0nmod10s20000000000p1e1e-50sig0.0001g0.99b0.1_lstm2.err
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g-5
#SBATCH -N 1
#SBATCH --workdir=/home/codylong/wishart/workdir
cd /home/codylong/wishart/
mpirun -prot -srun -n 1 python train_a3c_gym.py 32 --steps 20000000000 --eval-interval 2000000 --env cc-10k-v0 --outdir /gss_gpfs_scratch/codylong/wishart/old_origin_old_reward --gamma 0.99 --eps 1e-50 --nmod 10 --sigma 0.0001 --beta 0.1 --reward-d-pow 1 --origin ' -5064.0,-4584.0,1496.0,116.0,-1151.0,9140.0,-16063.0,4158.0,3837.0,-9467.0' --arch LSTMFR