#!/bin/bash
#SBATCH --job-name=cc-100k-v0nmod10s20000000000p1e1e-50sig0.0001g0.999999b0.1
#SBATCH --output=cc-100k-v0nmod10s20000000000p1e1e-50sig0.0001g0.999999b0.1.out
#SBATCH --error=cc-100k-v0nmod10s20000000000p1e1e-50sig0.0001g0.999999b0.1.err
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g-5
#SBATCH -N 1
#SBATCH --workdir=/home/codylong/wishartbump/workdir
cd /home/codylong/wishartbump/
mpirun -prot -srun -n 1 python train_a3c_gym.py 32 --steps 20000000000 --eval-interval 2000000 --env cc-100k-v0 --outdir /gss_gpfs_scratch/codylong/wishart/roundbumpgame --gamma 0.999999 --eps 1e-50 --nmod 10 --sigma 0.0001 --beta 0.1 --reward-d-pow 1 --load /gss_gpfs_scratch/codylong/wishart/roundbumpgame/20180620T103634.818444/332358667
