#!/bin/bash
#SBATCH --job-name=controlk10sig0.0001msteps1000exprandmtypeload
#SBATCH --output=controlk10sig0.0001msteps1000exprandmtypeload.out
#SBATCH --error=controlk10sig0.0001msteps1000exprandmtypeload.err
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g-4
#SBATCH -N 1
#SBATCH --workdir=/home/codylong/wishart/control/workdir
cd /home/codylong/wishart/control/
mpirun -prot -srun -n 2 python ControlClasses.py 1000 rand 10 1e-50 0.0001 load