#!/bin/bash
#SBATCH --job-name=controlk25sig0.0001msteps2000000000exprandmtypeload
#SBATCH --output=controlk25sig0.0001msteps2000000000exprandmtypeload.out
#SBATCH --error=controlk25sig0.0001msteps2000000000exprandmtypeload.err
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g-4
#SBATCH -N 1
#SBATCH --workdir=/home/codylong/wishart/control/workdir
cd /home/codylong/wishart/control/
mpirun -prot -srun -n 32 python ControlClasses.py 2000000000 rand 25 1e-50 0.0001 load