#!/bin/bash
#SBATCH --job-name=cc-100k-v0nmod250s20000000000p3e1e-50sig0.0001g0.9b1.0
#SBATCH --output=cc-100k-v0nmod250s20000000000p3e1e-50sig0.0001g0.9b1.0.out
#SBATCH --error=cc-100k-v0nmod250s20000000000p3e1e-50sig0.0001g0.9b1.0.err
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g-5
#SBATCH -N 1
#SBATCH --workdir=/home/codylong/wishart/workdir
cd /home/codylong/wishart/
mpirun -prot -srun -n 1 python train_a3c_gym.py 32 --steps 20000000000 --eval-interval 2000000 --env cc-100k-v0 --outdir /gss_gpfs_scratch/codylong/wishart/output_cc_prec --gamma 0.9 --eps 1e-50 --nmod 250 --sigma 0.0001 --beta 1.0 --reward-d-pow 3 --load /gss_gpfs_scratch/codylong/wishart/output_cc_prec/20180608T182421.146305/48170961
