#!/bin/bash
#SBATCH --job-name=cc-10k-v0nmod100s20000000000p3e1e-50sig0.0001g0.9b0.1_lstm
#SBATCH --output=cc-10k-v0nmod100s20000000000p3e1e-50sig0.0001g0.9b0.1_lstm.out
#SBATCH --error=cc-10k-v0nmod100s20000000000p3e1e-50sig0.0001g0.9b0.1_lstm.err
#SBATCH --exclusive
#SBATCH --partition=ser-par-10g-5
#SBATCH -N 1
#SBATCH --workdir=/home/jhhalverson/wishart/workdir
cd /home/jhhalverson/wishart/
mpirun -prot -srun -n 1 python train_a3c_gym.py 32 --steps 20000000000 --eval-interval 2000000 --env cc-10k-v0 --outdir /gss_gpfs_scratch/codylong/wishart/output_cc_prec --gamma 0.9 --eps 1e-50 --nmod 100 --sigma 0.0001 --beta 0.1 --reward-d-pow 3 --load /home/jhhalverson/wishart/output_cc_prec/20180614T125849.996178/24000634 --arch LSTMFR
